### ISSUE TITLE
Plugin impacts/hinders typing in some timestamps HH:MM format followed by ENTER

### ISSUE THREAD

**Issue by Alicecomma** [KraXen72/obsidian-emoji-autocomplete#1]
Hi,

I type in timestamps (i.e 19:14, ENTER) and the following things happen:

- :11 suggests clock11, 911, clock1130
- :12 suggests 1234, u7121, clock12, clock1230
- :13 suggests clock130, clock1130
- :21 suggests 7121
- :23 suggests 1234, clock230, clock1230
- :27 suggests u5272
- :30 suggests every clock..30 and u6307
- :33 suggests u5733, clock330
- :34 suggests 1234
- :40 suggests 5408
- :43 suggests clock430
- :52 suggests clock5272
- :53 suggests 7533, clock530
- :54 suggests u5408
- :55 suggests u55b6

This makes it inconsistent when typing in timestamps whether an emoji appears instead of the time or whether it works without emoji. I'd like entering times in the HH:MM format to be exempt from autocomplete

(This seems duplicate of https://github.com/phibr0/obsidian-emoji-shortcodes/issues/36 --)

I've also found that replacing with `this.queryRegex=new RegExp(/(?:^|\s):[^\s:0][^:]*$/);` fixes this (possibly overcorrecting)

**Comment by KraXen72** [comment]
i'll take a look, thanks for reporting!
