### ISSUE TITLE
Option to disable trigger in inline fields (aka. `key::value`)

### ISSUE THREAD

**Issue by Vinfall** [KraXen72/obsidian-emoji-autocomplete#2]
Thank you for making this plugin! I switched from Emoji Shortcodes today and discovered that this behavior still exists, hence the issue.

**What happened**:

In Obsidian, it's possible to add inline metadata/fields/whatever it's called in the following format (besides adding them in frontmatter):

```md
sleep::7.4
food:: 🥗
```

And as `::` contains a `:` sometimes the result would become `food:🥗` if I forget to add the leading indicator, which is no longer a valid metadata and would cause issue in DataviewJS queries.

I hope you could prevent this by default, or at least add an option to disable this.

**Expected behavior**:
1. if there is exactly two `:`, emoji does not autocomplete
2. if there is only one or odd numbers of `:` (in the case of `:::salad` before autocompletion), emoji would autocomplete as usual

**Comment by Vinfall** [comment]
Ops, I forgot to mention another issue so just leave it here.

Emoji autocomplete would be triggered even if `:` is wrapped (escaped?) by `, I assume this is not intended:

```md
# This is normal
:salad
# This is unexpected
`:`salad
# This is unexpected too
`::`salad
```

**Comment by KraXen72** [comment]
so, if i understand correctly, the first issue is that if you type food::something, emoji autocomplete tries to compelte for `something`? I don't know if i understand it correctly, if not, please let me know. regarding it's solution, there isn't really a good way to determine even/odd number of characters using RegEx, so i'd have to do that in JS, which id' like to avoid. I could extend the `Trigger on first letter` setting's off variant to not trigger if there's something like this: `word::whatever`, we'll see how that goes.  

for the second issue, it's not intended, but i havent't though of it initially. I'll see if i can fix it.

**Comment by Vinfall** [comment]
> the first issue is that if you type food::something, emoji autocomplete tries to complete for something?

Yes, sorry I did not add some examples like the second issue. I can't think up a solution either ~~but become accustomed to it so it's fine~~. Hmm, I noticed that not only `::` would trigger emoji complete, but many other combinations. The regex should be probably more restrictive I guess?

```md
# Normal
:salad
# Weird but acceptable
::salad
# Weird
:~salad
:$salad
:#salad
:%salad
...
```

Also, you don't really need to determine even/odd number of colon `:`, covering the first three cases would suffice IMO.

```md
# This would trigger emoji autocomplete
:salad
# This one won't (normal text in inline field)
::salad
# This one would trigger again (add emoji in inline field)
:::salad
# This one won't too, but I think it's very unlikely to happen. Who would type this way😶‍🌫️
::::salad
```

Regarding the second issue, I upgraded to 1.2.1 and it still happens to me after disabling all other community plugins & reloading.
Now it becomes:

```md
# This is normal
:salad
# This would still trigger emoji autocomplete
`:`salad
# This one is fixed
`::`salad
```

**Comment by KraXen72** [comment]
oh yeah i haven't fixed the \`:\`salad thing yet i forgot about that. I don't have too much time right now, but i'll eventually get to it. Is the first issue atleast fixed?

make sure you have the strict trigger option enabled in Emoji Autocomplete Settings - it should be enabled by default but still.

also, what is the use-case for typing \`:\`salad lol.

**Comment by Vinfall** [comment]
> make sure you have the strict trigger option enabled in Emoji Autocomplete Settings

Yes, I checked settings and `stricter autocomplete trigger` is already selected. Full `data.json` attached in the end if it helps.

> Is the first issue at least fixed?

If you mean `::salad`, sadly no. And more examples are provided in the first code block in my reply above. I discovered those when typing scripts in code blocks (like `scp remote:~/wherever/file ./file`.

At least the second issue is partially solved, and like you said, \`:\`salad is a rare edge case so just ignore that. Please take your time, I don't mind waiting for a few days or even months.

`data.json`:
```jsonc
{
  "immediateReplace": true,
  "suggester": true,
  "considerHistory": true,
  "historyLimit": 25,
  "history": [
    "rice",
    "duck",
    "green_salad",
    "kiss",
    "sleepy",
    "middle_finger",
    "six_pointed_star",
    "dotted_line_face",
    "star_of_david",
    "facepalm",
    "chicken",
    "hair_pick",
    "iphone",
    "love",
    "santa",
    "leafy_green"
  ],
  "highlightMatches": true,
  "strictTrigger": true,
  "triggerFromFirst": true,
  "emojiSupported": {
// This has too many lines so I omit them.
  },
  "hideUnsupported": true,
  "tagSearch": true,
  "tagShowShortcode": false,
  "latinize": true,
  "polyfillFlags": false
}
```

**Comment by KraXen72** [comment]
oh yeah, i still trigger for `::salad` but i no longet trigger for `key::salad` with key being whatever, since that's the dataview syntax. I don't think `::salad` does anything for dataview? but i could be wrong.

**Comment by Vinfall** [comment]
That's right, `::salad` is weird enough. Things like `key:~value` (in the format of `scp remote:~/wherever/file ./file`) are still valid though. I'm closing this anyway as these cases normally won't happen _that_ frequently.
