### ISSUE TITLE
Dataview inline field incompatibility

### ISSUE THREAD

**Issue by symph0nic** [KraXen72/obsidian-emoji-autocomplete#7]
Hello! Loving this plugin so far. The only issue I have is that if you try to insert an emoji into a dataview inline field it doesn't work. For example, I have daily notes where I use emoji for statuses, such as:

Writing:: 🟩 

Except when using the plugin, after the inline field signifier of "::" , entering a space then ":" to bring up the emoji picker doesn't work.

Thanks!

**Comment by KraXen72** [comment]
You have to turn off `stricter autocomplete trigger` in the settings. people were complaining about it triggering when writing dataview inline fields, so by default, it does not trigger.

**Comment by symph0nic** [comment]
That doesn't seem to have made any difference. With that option disabled, I get the popup when entering times, but not after the :: : sequence. Sorry if I'm doing something dumb!

**Comment by KraXen72** [comment]
works for me. try doing like `:: :white_ch`. if you want it to trigger from the first character, turn on `trigger from first character`

**Comment by symph0nic** [comment]
Ok maybe something else is interfering then, cos it's not working for me even with that option enabled. See attached.

https://github.com/user-attachments/assets/c92d45e6-5d2d-4110-b9ba-9cfafb051411

**Comment by symph0nic** [comment]
Ok, ignore me. I disabled all plugins and it worked fine. Re-enabled one by one and I no longer have the issue - there must have been some weird interaction with another plugin but I can't reproduce any more.
