### ISSUE TITLE
Doesn't work with Tasks?

### ISSUE THREAD

**Issue by tbergeron** [KraXen72/obsidian-emoji-autocomplete#9]
For some reason the plugin doesn't get trigger when typing `:` when using in a task:

ie.

```
- This is going to trigger the popup when typing :
- [ ] This won't trigger the popup when typing :
```

Any reason why? Could that be fixed?

Thanks!

---

SYSTEM INFO:
	Obsidian version: v1.7.7
	Installer version: v1.5.11
	Operating system: Darwin Kernel Version 24.1.0: Thu Oct 10 21:05:14 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8103 24.1.0
	Login status: logged in
	Language: en
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Obsidian Nord v0.2.0
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 38
	Plugins enabled: 32
		1: Kanban v2.0.51
		2: Natural Language Dates v0.6.2
		3: Folder notes v1.7.32
		4: Highlightr v1.2.2
		5: Advanced Tables v0.22.1
		6: Reminder v1.1.16
		7: Automatic Table Of Contents v1.5.0
		8: Dataview v0.5.67
		9: Recent Files v1.7.2
		10: Tasks v7.14.0
		11: Tag Wrangler v0.6.1
		12: Share Note v0.8.17
		13: File Hider v1.1.1
		14: Remember cursor position v1.0.9
		15: List Callouts v1.2.9
		16: Badges v1.1.0
		17: Callout Manager v1.1.0
		18: Git v2.30.1
		19: Hotkeys++ v0.2.7
		20: File Cleaner Redux v1.2.0
		21: Plugin Update Tracker v1.6.0
		22: Text Snippets v0.1.2
		23: Force note view mode v1.2.2
		24: Link Embed v2.0.12
		25: Omnisearch v1.25.1
		26: Text Extractor v0.5.2
		27: Emoji Autocomplete v1.4.1
		28: Auto Link Title v1.5.4
		29: Multi-Column Markdown v0.9.1
		30: Local Quotes v1.9.0
		31: Activity Heatmap v1.0.4
		32: Copilot v2.7.4

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by KraXen72** [comment]
![image](https://github.com/user-attachments/assets/fe25deef-d065-4629-bd48-14ddb524f749)
it works for me. can you please try opening the developer tools -> console and send screenshots of any errors that are there that could be related to this plugin?
On mac it should be  cmd-alt-i according to [this](https://forum.obsidian.md/t/how-to-access-developer-tools-in-v0-8-14/5820/2)

**Comment by tbergeron** [comment]
> ![image](https://private-user-images.githubusercontent.com/21956756/391473878-fe25deef-d065-4629-bd48-14ddb524f749.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNjA0NjEsIm5iZiI6MTczMzE2MDE2MSwicGF0aCI6Ii8yMTk1Njc1Ni8zOTE0NzM4NzgtZmUyNWRlZWYtZDA2NS00NjI5LWJkNDgtMTRkZGI1MjRmNzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE3MjI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMzAzMzgwNzAwN2RmN2E0NDI3NWVlZDg4ZjgwNmMzMDc5YjU5OTQ3ZmE5NjFjZDE2OWE3NzI4YTJmM2UwYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q0IBedOZ2AJdbgwWPSapgESYiYltpuXwBooviHkELbA) it works for me. can you please try opening the developer tools -> console and send screenshots of any errors that are there that could be related to this plugin? On mac it should be cmd-alt-i according to [this](https://forum.obsidian.md/t/how-to-access-developer-tools-in-v0-8-14/5820/2)

Nothing seems to show up in the dev console at all. Nothing weird happening, it just won't show the popup at all. I've made a video to demonstrate the problem:

https://github.com/user-attachments/assets/472642d7-be75-41d8-8504-464d3f3c58b2

Hope this helps and thanks for your support and quick answer. Don't hesitate if you need anything else from me.

**Comment by KraXen72** [comment]
Only thing that comes to mind, can you try with the tasks plugin turned off? obviously, if that's the issue, i'll try to debug it, as it's supposed to work with the Tasks plugin as well.

**Comment by tbergeron** [comment]
When I disable the Tasks plugin, it does work 🤷 so it seems to be definitively related to it. Let me know if you need anything else, thanks!

**Comment by tbergeron** [comment]
> Only thing that comes to mind, can you try with the tasks plugin turned off? obviously, if that's the issue, i'll try to debug it, as it's supposed to work with the Tasks plugin as well.

I just noticed that it's started working after re-enabling the Tasks plugin 😆 🤷 I have no idea why this happened but now somehow the exact same tests do work. So sorry for wasting your time! Thanks for the support and keep it up!

**Comment by KraXen72** [comment]
glad it was resolved, no worries
